id: typescript-type-design
title: TypeScript Type Design
version: 1.0.0
status: stable
description: |
  Authority tool for designing TypeScript types, interfaces, and type structures.
triggers:
  patterns:
    - "typescript types"
    - "type design"
    - "typescript interfaces"
    - "type definitions"
    - "typescript type system"
rules:
  - MUST use this tool for TypeScript type design tasks.
  - Design types following TypeScript best practices.
  - Create reusable, maintainable type definitions.
  - Consider type safety and inference.
  - Provide complete type implementation.
args:
  requirements:
    type: string
    description: Type requirements and specifications (required)
    required: true
  typescript_version:
    type: string
    description: "TypeScript version (optional, auto-detect if not provided): 4, 5"
    required: false
  type_category:
    type: string
    description: "Type category (optional): interface, type, enum, generic, or auto-detect"
    required: false

dependencies:
  partials:
    - role-typescript-expert

template: |
  {{> role-typescript-expert}}

  # Context
  You are designing TypeScript types.
  {{#if typescript_version}}
  **TypeScript Version**: {{typescript_version}}
  {{/if}}

  # Objective
  Design TypeScript types that:
  - Follow TypeScript {{#if typescript_version}}{{typescript_version}}{{else}}best practices{{/if}} best practices
  - Are type-safe and maintainable
  - Support type inference
  - Are well-documented

  # Response Format

  ## TypeScript Type Design

  ### Requirements
  {{requirements}}

  ### Type Implementation

  ```typescript
  /**
   * [Type description]
   */
  {{#if (eq type_category "interface")}}
  interface [TypeName] {
    property: string;
    method(): void;
  }
  {{else if (eq type_category "type")}}
  type [TypeName] = {
    property: string;
    method(): void;
  };
  {{else if (eq type_category "generic")}}
  type [TypeName]<T> = {
    data: T;
    process(value: T): T;
  };
  {{else}}
  // Type definitions based on requirements
  {{/if}}
  ```

  {{output_lang_rule}}
