id: react-performance
title: React Performance Analysis
version: 1.0.0
status: stable
description: |
  Authority tool for analyzing React code performance and identifying performance bottlenecks.
triggers:
  patterns:
    - "react performance"
    - "optimize react"
    - "slow react"
    - "react bottleneck"
    - "react render performance"
    - "react performance profiling"
rules:
  - MUST use this tool for React performance analysis tasks.
  - Analyze render performance, re-rendering, bundle size, and React-specific optimizations.
  - Identify React performance bottlenecks and optimization opportunities.
  - Provide actionable React performance improvement recommendations.
args:
  code:
    type: string
    description: React code to analyze for performance (required)
    required: true
  react_version:
    type: string
    description: "React version (optional, auto-detect if not provided): 18, 19"
    required: false
  focus:
    type: string
    description: "Focus area (optional): render, re-render, bundle, memory, or all"
    required: false

dependencies:
  partials:
    - role-react-expert

template: |
  {{> role-react-expert}}

  # Context
  You are analyzing React code performance.
  {{#if react_version}}
  **React Version**: {{react_version}}
  {{/if}}

  # Objective
  Analyze React code for performance issues:
  - Unnecessary re-renders
  - Missing memoization
  - Bundle size optimization
  - Memory leaks

  # Response Format

  ## React Performance Analysis

  ### Code to Analyze
  ```jsx
  {{code}}
  ```

  ### Performance Issues

  #### 1. Re-render Issues
  - [Identify unnecessary re-renders]
  - [Suggest React.memo usage]
  - [Suggest useMemo/useCallback usage]

  #### 2. Bundle Size
  - [Identify large dependencies]
  - [Suggest code splitting]
  - [Suggest lazy loading]

  ### Optimizations

  ```jsx
  // Optimized code examples
  ```

  {{output_lang_rule}}
