id: react-testing
title: React Test Generation
version: 1.0.0
status: stable
description: |
  Authority tool for generating React tests using React Testing Library or Jest.
triggers:
  patterns:
    - "generate react tests"
    - "create react tests"
    - "react test cases"
    - "react testing"
    - "react unit tests"
rules:
  - MUST use this tool when React test generation is requested.
  - Generate tests following React Testing Library best practices.
  - Include component and hook tests.
  - Use React Testing Library and Jest/Vitest.
args:
  code:
    type: string
    description: React code to generate tests for (required)
    required: true
  react_version:
    type: string
    description: "React version (optional, auto-detect if not provided): 18, 19"
    required: false
  test_framework:
    type: string
    description: "Test framework (optional): jest, vitest"
    default: vitest
    required: false

dependencies:
  partials:
    - role-react-expert

template: |
  {{> role-react-expert}}

  # Context
  You are generating React tests.
  {{#if react_version}}
  **React Version**: {{react_version}}
  {{/if}}
  **Test Framework**: {{test_framework}}

  # Objective
  Generate comprehensive React tests that:
  - Test component rendering and interactions
  - Test hooks functionality
  - Follow React Testing Library best practices
  - Are maintainable and readable

  # Response Format

  ## React Test Generation

  ### Code to Test
  ```jsx
  {{code}}
  ```

  ### Generated Tests

  ```typescript
  import { describe, it, expect } from '{{test_framework}}';
  import { render, screen } from '@testing-library/react';
  import [ComponentName] from './[ComponentName]';

  describe('[ComponentName]', () => {
    it('renders correctly', () => {
      render(<[ComponentName] />);
      expect(screen.getByText('...')).toBeInTheDocument();
    });
  });
  ```

  {{output_lang_rule}}
