id: nestjs-controller-design
title: NestJS Controller Design
version: 1.0.0
status: stable
description: |
  Authority tool for designing NestJS controllers and endpoints.
triggers:
  patterns:
    - "nestjs controller"
    - "nestjs api"
    - "nestjs endpoint"
    - "nestjs route"
    - "nestjs handler"
rules:
  - MUST use this tool for NestJS controller design tasks.
  - Design controllers following NestJS best practices.
  - Create RESTful endpoints with proper decorators.
  - Include proper DTOs and validation.
  - Provide complete controller implementation.
args:
  requirements:
    type: string
    description: Controller requirements and specifications (required)
    required: true
  nestjs_version:
    type: string
    description: "NestJS version (optional, auto-detect if not provided): 9, 10"
    required: false
  use_typescript:
    type: boolean
    description: Use TypeScript
    default: true
    required: false

dependencies:
  partials:
    - role-nestjs-expert

template: |
  {{> role-nestjs-expert}}

  # Context
  You are designing NestJS controllers.
  {{#if nestjs_version}}
  **NestJS Version**: {{nestjs_version}}
  {{/if}}

  # Objective
  Design NestJS controllers that:
  - Follow NestJS {{#if nestjs_version}}{{nestjs_version}}{{else}}best practices{{/if}} best practices
  - Use proper decorators
  - Include DTOs and validation
  - Are well-structured and maintainable

  # Response Format

  ## NestJS Controller Design

  ### Requirements
  {{requirements}}

  ### Controller Implementation

  ```typescript
  import { Controller, Get, Post, Body } from '@nestjs/common';
  import { [ServiceName]Service } from './[service-name].service';
  import { Create[Resource]Dto } from './dto/create-[resource].dto';

  @Controller('[resource]')
  export class [Resource]Controller {
    constructor(private readonly service: [ServiceName]Service) {}

    @Get()
    findAll() {
      return this.service.findAll();
    }

    @Post()
    create(@Body() createDto: Create[Resource]Dto) {
      return this.service.create(createDto);
    }
  }
  ```

  {{output_lang_rule}}
