id: laravel-code-review
title: Laravel Code Review
description: |
  Authority tool for comprehensive Laravel code review. RULES: 1. MUST use this tool when Laravel code review is requested. 2. Analyze Laravel code quality, potential bugs, security issues, and Laravel best practices. 3. Check PSR standards, Laravel conventions, and framework-specific patterns. 4. Provide structured feedback with severity levels. 5. Follow strict_mode rules when enabled.
triggers:
  patterns:
    - "review laravel"
    - "check laravel code"
    - "laravel code quality"
    - "analyze laravel code"
    - "laravel code audit"
    - "review php laravel"
args:
  code:
    type: string
    description: Laravel code to review (required)
    required: true
  php_version:
    type: string
    description: "PHP version (optional, auto-detect if not provided): 8.1, 8.2, 8.3"
    required: false
  laravel_version:
    type: string
    description: "Laravel version (optional, auto-detect if not provided): 10, 11"
    required: false
  strict_mode:
    type: boolean
    description: Enable strict validation mode with zero-tolerance for issues
    default: false
    required: false
  focus:
    type: string
    description: "Focus areas (optional): security, performance, maintainability, eloquent, or all"
    required: false
  check_psr:
    type: boolean
    description: Check PSR standards compliance
    default: true
    required: false

dependencies:
  partials:
    - role-laravel-expert

template: |
  {{> role-laravel-expert}}

  # Context
  You are performing a comprehensive code review on Laravel code.
  {{#if php_version}}
  **PHP Version**: {{php_version}}
  {{/if}}
  {{#if laravel_version}}
  **Laravel Version**: {{laravel_version}}
  {{/if}}

  # Objective
  Analyze the provided Laravel code for:
  - Code quality and maintainability
  - Potential bugs and security vulnerabilities
  - Performance issues (especially Eloquent queries)
  - Laravel best practices adherence
  - PSR standards compliance
  - SOLID principles compliance
  - Laravel-specific patterns and conventions

  # Style
  Provide structured output in Markdown format with clear sections and severity indicators.

  # Tone
  Professional, constructive, and educational. Focus on Laravel-specific improvement opportunities.

  # Audience
  Laravel developers working on the codebase.

  # Response Format

  ## Laravel Code Review Report

  ### Code Overview
  ```php
  {{code}}
  ```

  {{#if focus}}
  ### Focus Areas
  **Requested focus**: {{focus}}
  {{/if}}

  {{#if strict_mode}}
  ### ⚠️ Strict Mode Enabled
  Applying zero-tolerance validation rules. All issues must be addressed.
  {{/if}}

  ### Analysis

  #### 1. Code Quality Assessment
  - **Overall Rating**: [Rate from 1-10]
  - **Maintainability**: [Assessment]
  - **Readability**: [Assessment]
  - **Complexity**: [Assessment]
  - **Laravel Conventions**: [Assessment]

  {{#if check_psr}}
  #### 2. PSR Standards Compliance
  - **PSR-1**: [Check basic coding standard]
  - **PSR-12**: [Check extended coding style]
  - **PSR-4**: [Check autoloading standard]
  - **PSR-5/PSR-19**: [Check PHPDoc standard]
  {{/if}}

  #### 3. Issues Found

  {{#if strict_mode}}
  **Critical Issues** (Must Fix):
  - [List all critical issues]

  **High Priority Issues**:
  - [List high priority issues]

  **Medium Priority Issues**:
  - [List medium priority issues]

  **Low Priority / Suggestions**:
  - [List suggestions]
  {{else}}
  **Issues by Severity**:
  - 🔴 **Critical**: [List critical issues]
  - 🟠 **High**: [List high priority issues]
  - 🟡 **Medium**: [List medium priority issues]
  - 🟢 **Low**: [List suggestions]
  {{/if}}

  #### 4. Laravel-Specific Issues

  **Controller Issues**:
  - [Check controller structure, method organization, dependency injection]
  - [Check resource controller usage]
  - [Check authorization and validation]

  **Model Issues**:
  - [Check Eloquent model structure]
  - [Check relationships definition]
  - [Check accessors, mutators, scopes]
  - [Check mass assignment protection]

  **Eloquent Query Issues**:
  - [Check for N+1 problems]
  - [Check eager loading usage]
  - [Check query optimization]
  - [Check database indexes]

  **Service Layer Issues**:
  - [Check service class structure]
  - [Check business logic separation]
  - [Check dependency injection]

  **Route Issues**:
  - [Check route organization]
  - [Check route model binding]
  - [Check middleware usage]

  **Form Request Issues**:
  - [Check validation rules]
  - [Check authorization logic]
  - [Check custom validation messages]

  #### 5. Security Concerns

  **Laravel Security Features**:
  - [Check CSRF protection]
  - [Check XSS prevention]
  - [Check SQL injection protection (Eloquent usage)]
  - [Check mass assignment protection]
  - [Check authentication and authorization]
  - [Check input validation and sanitization]

  **Security Vulnerabilities**:
  - [Identify Laravel-specific security issues]
  - [Suggest Laravel security improvements]

  #### 6. Performance Analysis

  **Laravel Performance Issues**:
  - [Check Eloquent query performance]
  - [Check N+1 query problems]
  - [Check eager loading opportunities]
  - [Check caching usage]
  - [Check queue usage for heavy operations]
  - [Check database query optimization]

  **Performance Optimizations**:
  - [Suggest Laravel-specific optimizations]
  - [Suggest caching strategies]
  - [Suggest database optimization]

  #### 7. Laravel Best Practices Compliance

  **Framework Conventions**:
  - [Check naming conventions]
  - [Check directory structure]
  - [Check service provider usage]
  - [Check middleware organization]
  - [Check event/listener patterns]

  **Laravel {{#if laravel_version}}{{laravel_version}}{{else}}Best Practices{{/if}}**:
  - [Check version-specific best practices]
  - [Check modern Laravel patterns]
  - [Identify anti-patterns]
  - [Suggest Laravel-specific improvements]

  #### 8. SOLID Principles Compliance

  - **Single Responsibility**: [Check SRP violations in Laravel context]
  - **Open/Closed**: [Check extensibility]
  - **Liskov Substitution**: [Check inheritance patterns]
  - **Interface Segregation**: [Check interface usage]
  - **Dependency Inversion**: [Check dependency injection patterns]

  #### 9. Recommendations

  **Immediate Actions**:
  - [Prioritized list of must-fix issues]

  **Laravel-Specific Improvements**:
  - [Laravel pattern suggestions]
  - [Framework feature utilization]
  - [Code examples for fixes]

  **Refactoring Opportunities**:
  - [Suggest refactoring to Laravel patterns]
  - [Suggest service layer introduction]
  - [Suggest repository pattern if applicable]

  ### Summary
  [Overall assessment and next steps for Laravel codebase]

  {{output_lang_rule}}
