id: api-design
title: API Design
version: 1.0.0
status: stable
description: |
  Authority tool for RESTful API design and architecture.
triggers:
  patterns:
    - "design api"
    - "create api"
    - "api endpoint"
    - "rest api"
    - "api architecture"
    - "api structure"
rules:
  - MUST use this tool for API design tasks
  - Design RESTful APIs following industry best practices
  - Consider backend and frontend integration patterns
  - Provide complete API specification with examples
args:
  resource:
    type: string
    description: Resource name (e.g., users, products, orders)
    required: true
  requirements:
    type: string
    description: API requirements and use cases
    required: true
  backend_framework:
    type: string
    description: Backend framework (optional, e.g., laravel, express, django, spring)
    required: false
  frontend_framework:
    type: string
    description: Frontend framework (optional, e.g., vue, react, angular)
    required: false
  include_auth:
    type: boolean
    description: Include authentication and authorization design
    default: true
    required: false
  include_validation:
    type: boolean
    description: Include request validation rules
    default: true
    required: false
  version:
    type: string
    description: API version (e.g., v1, v2)
    default: v1
    required: false

dependencies:
  partials:
    - role-expert

template: |
  {{> role-expert}}

  # Context
  You are designing a RESTful API specification.

  {{#if backend_framework}}
  **Backend Framework**: {{backend_framework}}
  {{/if}}
  {{#if frontend_framework}}
  **Frontend Framework**: {{frontend_framework}}
  {{/if}}

  # Objective
  Design a complete, production-ready API specification including:
  - RESTful endpoint structure
  - Request/response formats
  - Authentication and authorization
  - Validation rules
  - Error handling
  - Frontend integration patterns

  # Style
  Provide comprehensive API documentation with clear specifications and examples.

  # Tone
  Technical, comprehensive, and implementation-focused.

  # Audience
  Full-stack developers implementing the API and frontend integration.

  # Response Format

  ## API Design Specification

  ### Resource: {{resource}}
  **API Version**: {{version}}

  ### Requirements
  {{requirements}}

  {{#if include_auth}}
  ### Authentication & Authorization
  - **Authentication Method**: [Specify: JWT, OAuth, Session-based, etc.]
  - **Authorization Levels**: [Define roles/permissions]
  - **Protected Endpoints**: [List which endpoints require auth]
  - **Token Management**: [Describe token refresh and expiration]
  {{/if}}

  ### API Endpoints

  #### 1. List Resources
  ```
  GET /api/{{version}}/{{resource}}
  ```

  **Query Parameters**:
  - `page`: Page number (pagination)
  - `per_page` or `limit`: Items per page
  - `sort`: Sort field and direction (e.g., `sort=name:asc`)
  - `filter`: Filter criteria (e.g., `filter[status]=active`)
  - `fields`: Field selection (sparse fieldsets)
  - `include`: Related resources to include

  **Response** (200 OK):
  ```json
  {
    "data": [
      {
        "id": "1",
        "type": "{{resource}}",
        "attributes": {
          // Resource attributes
        },
        "relationships": {}
      }
    ],
    "meta": {
      "pagination": {
        "page": 1,
        "per_page": 15,
        "total": 100,
        "total_pages": 7
      }
    },
    "links": {
      "self": "/api/{{version}}/{{resource}}?page=1",
      "first": "/api/{{version}}/{{resource}}?page=1",
      "last": "/api/{{version}}/{{resource}}?page=7",
      "prev": null,
      "next": "/api/{{version}}/{{resource}}?page=2"
    }
  }
  ```

  #### 2. Get Single Resource
  ```
  GET /api/{{version}}/{{resource}}/{id}
  ```

  **Response** (200 OK):
  ```json
  {
    "data": {
      "id": "1",
      "type": "{{resource}}",
      "attributes": {
        // Resource attributes
      },
      "relationships": {}
    }
  }
  ```

  **Error Response** (404 Not Found):
  ```json
  {
    "errors": [
      {
        "status": "404",
        "code": "RESOURCE_NOT_FOUND",
        "title": "Resource Not Found",
        "detail": "The requested resource does not exist."
      }
    ]
  }
  ```

  #### 3. Create Resource
  ```
  POST /api/{{version}}/{{resource}}
  ```

  {{#if include_validation}}
  **Request Validation Rules**:
  - [List validation rules for each field]
  - [Specify required vs optional fields]
  - [Define data types and constraints]
  {{/if}}

  **Request Body**:
  ```json
  {
    "data": {
      "type": "{{resource}}",
      "attributes": {
        // Resource attributes
      }
    }
  }
  ```

  **Response** (201 Created):
  ```json
  {
    "data": {
      "id": "1",
      "type": "{{resource}}",
      "attributes": {
        // Created resource attributes
      }
    }
  }
  ```

  #### 4. Update Resource
  ```
  PUT /api/{{version}}/{{resource}}/{id}    # Full update
  PATCH /api/{{version}}/{{resource}}/{id}  # Partial update
  ```

  **Request Body**: Same structure as Create

  **Response** (200 OK): Same as Get Single Resource

  #### 5. Delete Resource
  ```
  DELETE /api/{{version}}/{{resource}}/{id}
  ```

  **Response** (204 No Content)

  ### Error Handling

  #### Standard Error Response Format
  ```json
  {
    "errors": [
      {
        "status": "HTTP_STATUS_CODE",
        "code": "ERROR_CODE",
        "title": "Error Title",
        "detail": "Detailed error message",
        "source": {
          "pointer": "/data/attributes/field",
          "parameter": "query_param"
        }
      }
    ]
  }
  ```

  #### HTTP Status Codes
  - `200 OK`: Success
  - `201 Created`: Resource created successfully
  - `204 No Content`: Success (no content to return)
  - `400 Bad Request`: Invalid request syntax or parameters
  - `401 Unauthorized`: Authentication required
  - `403 Forbidden`: Authorization failed
  - `404 Not Found`: Resource not found
  - `409 Conflict`: Resource conflict (e.g., duplicate)
  - `422 Unprocessable Entity`: Validation failed
  - `429 Too Many Requests`: Rate limit exceeded
  - `500 Internal Server Error`: Server error

  ### Best Practices

  1. **RESTful Design**: Follow REST principles strictly
     - Use proper HTTP methods (GET, POST, PUT, PATCH, DELETE)
     - Use proper HTTP status codes
     - Use resource-based URLs

  2. **Consistent Response Format**: 
     - Use JSON:API specification or consistent custom format
     - Maintain consistent structure across all endpoints

  3. **Pagination**: 
     - Always paginate list endpoints
     - Provide pagination metadata
     - Support cursor-based or offset-based pagination

  4. **Filtering & Sorting**: 
     - Support query parameters for filtering
     - Support sorting by multiple fields
     - Document all supported query parameters

  5. **Versioning**: 
     - Use URL versioning (`/api/v1/`) or header versioning
     - Maintain backward compatibility when possible
     - Document versioning strategy

  6. **Error Handling**: 
     - Consistent error response format
     - Provide meaningful error messages
     - Include error codes for programmatic handling

  7. **Documentation**: 
     - Provide OpenAPI/Swagger documentation
     - Document all endpoints, parameters, and responses
     - Include examples

  8. **Security**: 
     - Validate all inputs
     - Sanitize outputs
     - Use HTTPS
     - Implement rate limiting
     - Protect against common vulnerabilities (SQL injection, XSS, etc.)

  9. **Performance**: 
     - Implement caching strategies
     - Optimize database queries
     - Use compression (gzip)
     - Consider CDN for static resources

  10. **Testing**: 
     - Provide test endpoints or sandbox environment
     - Document testing procedures
     - Include example requests/responses

  ### Implementation Notes

  {{#if backend_framework}}
  **Backend Framework**: {{backend_framework}}
  - [Provide framework-specific implementation guidance]
  - [Reference framework best practices]
  {{/if}}

  {{#if frontend_framework}}
  **Frontend Framework**: {{frontend_framework}}
  - [Provide framework-specific integration patterns]
  - [Reference framework best practices]
  {{/if}}

  {{#unless backend_framework}}
  **Backend Implementation**:
  - Choose appropriate framework based on requirements
  - Follow framework-specific best practices
  - Implement proper error handling and validation
  {{/unless}}

  {{#unless frontend_framework}}
  **Frontend Integration**:
  - Choose appropriate HTTP client library
  - Implement proper error handling
  - Handle loading states and caching
  {{/unless}}

  {{output_lang_rule}}
